data:
  train_size: 50000
  seed: 1111
train:
  lr: 0.1
  resume: false
  optimizer: musgd
  epochs: 150
  batch_size: 128
  test_batch_size: 128
  weight_decay: 0.0005
  num_workers: 0
  test_num_workers: 0
  momentum: 0.9
  use_progress_bar: false
  criterion: l2
model:
  arch: resnet18
  width_mult: 1
  growth_factor: 2
  save_base_shapes: false
  load_base_shapes: resnet18.bsh
  coord_check: false
  coord_check_nsteps: 3
  coord_check_nseeds: 1
